### PR TITLE
added support for ADM 

### PR DESCRIPTION
**Pull request by Diegopyl1209**
https://user-images.githubusercontent.com/80992641/194728375-a9c2b45b-9a33-4124-9cdf-c38fe6201ff9.mp4

I changed the default download directory from: "/Aniyomi/downloads" to "/Downloads/Aniyomi/" because ADM can only download to the "downloads" and "documents" folders.
without this change ADM would give an error saying that you do not have access to the directory

### CODE REVIEW

**Comment by jmir1** [comment]
> Is this will be a new update? Because it's not working for me

This change will be included in the next update.

**Comment by logickoder** [comment]
Can this also be done for 1DM?

**Comment by 12ohit** [comment]
> Can this also be done for 1DM?

Umm, 1DM and 1DM+ support is already there.

**Comment by Diegopyl1209** [comment]
> > Can this also be done for 1DM?
> 
> Umm, 1DM and 1DM+ support is already there.

It probably refers to the fact that in adm you can directly play the video from aniyomi as if it were downloaded from the same application

**Comment by Diegopyl1209** [comment]
> Can this also be done for 1DM?

nope, 1dm without allowing to specify the download path from the intent

**Comment by logickoder** [comment]
Why wasn't this merged?

**Pull request closed without merging**
