### PR TITLE
Add refresh button in anime

### PR DESCRIPTION
**Pull request by Quickdesh**
Changes
---

- Added refresh button for anime pages (not for manga) 
 Its useful for users on devices other than mobile

Screenshot_20221019-130904-473

### CODE REVIEW

**Comment by jmir1** [comment]
why only for Anime page? 🤔

**Comment by Quickdesh** [comment]
Well... Idt anyone read Manga on a device other than phone.... Do they?

**Comment by jmir1** [comment]
i see.
then maybe we should make it for tablet ui only?

**Comment by Quickdesh** [comment]
I was not sure how the android TV registered the screen, so I added it as a general one. Should I switch it over to tablet only?

**Comment by jmir1** [comment]
no i think you can leave it like this but add it for the manga screen as well

**Comment by Quickdesh** [comment]
Alright, on it

**Comment by Quickdesh** [comment]
got busy right after I said on it lol,

added it to manga page too

**Comment by Quickdesh** [comment]
what in the fuck happened to the build

**Comment by jmir1** [comment]
Gradle can't find some dependencies for some reason.
Maybe the repos are down or something.
I'll re-run it later.

**Comment by jmir1** [comment]
It worked now :+1:

**Pull request closed without merging**
