### PR TITLE
add margin around player controls

### PR DESCRIPTION
**Pull request by Quickdesh**
Changes
---
- Moved the buttons inwards

Images
---

Before : 

Screenshot_20220408-000437 (1)

After :

Screenshot_20220408-165651

### CODE REVIEW

**Comment by jmir1** [comment]
i think it should be 10px on all sides. i think we can use the `windowInsetsController` to make sapce for a notch if it's there.

**Comment by Quickdesh** [comment]
the one who had the problem said it got fixed by using show content in display cutout settings

so I could just make it all 10 margin and leave it at then?

**Comment by jmir1** [comment]
> the one who had the problem said it got fixed by using show content in display cutout settings
> 
> so I could just make it all 10 margin and leave it at then?

For the time being, yes.

I think it just looks better with 10dp margin on all sides.

**Comment by Quickdesh** [comment]
Alright, I'll make that change then

**Review by jmir1 — APPROVED** [review]

**Pull request merged**
