### PR TITLE
Qol additions and fixes

### PR DESCRIPTION
**Pull request by Quickdesh**
Changes
---
- Rewrote the code for "Quality" Dialog to match with the other dialogs
- Fixed double tap play!/pause not working on the view itself
- Improved Seeking
    - Rewrote the code related to double tap seek
    - Player UI now hides while seeking
    - Player now pauses while seeking
- Replaced ugly grey square with better grey circle
-  Brightness and Volume levels now save on exiting a player session
- Made the middle icons smaller
- Fixed the background color of the volume and brightness bars
- Fixed the color for the cache progress in seekbar
- Added option to automatically go into PiP on exiting the player (in turn hide the PiP button)
- Changed preferences default values
    - Fast seeking is now default true
    - Auto open PiP is now default true
- When preserving watch position, external player begin from the start if watch position is same as duration

Images
---
Screenshot_20220630-025034~2

Screenshot_20220630-025158

Screenshot_20220630-025201

Screenshot_20220630-025031~2

Screenshot_20220630-025017~2

Screenshot_20220630-025026

Screenshot_20220630-025407

### CODE REVIEW

**Comment by 12ohit** [comment]
Closes #619

**Comment by Quickdesh** [comment]
Thanks lol

**Comment by Quickdesh** [comment]
Closes #629 and #143

**Comment by Rohan-511** [comment]
Will this ever complete?

**Comment by jmir1** [comment]
what do you mean? @Rohan-511

**Pull request merged**
