### PR TITLE
Icon Replacement (Suggestion)

### PR DESCRIPTION
**Pull request by Quickdesh**
Changes
---
- Renamed "**ic_tachi**" drawable to "**ic_ani**"
- Replaced the **tachiyomi** icon with one that better matches the **aniyomi** logo
- Resized the icon in to better match the original size of the **tachiyomi** icon

Images
---

Screenshot_20220323-203819
Screenshot_20220323-203813

Screenshot_20220323-203809
Screenshot_20220323-2038492

### CODE REVIEW

**Comment by Quickdesh** [comment]
ahh shit, I didn't realise it would show up with the previous commits. My bad, I am still learning all of this

**Comment by jmir1** [comment]
> ahh shit, I didn't realise it would show up with the previous commits. My bad, I am still learning all of this

Doesn't matter, the commit is gonna get squashed anyway.

**Comment by Quickdesh** [comment]
What do you mean by squashed?

**Comment by jmir1** [comment]
> What do you mean by squashed?
> 
> as in, since its the same commit, it will just have no change? something like that?

it means all the commits from this PR will be squashed into one on the master branch

**Pull request merged**
